# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "main" ]

jobs:
  release:
    permissions:
      contents: write
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2
      with:
        version: 8.5.1
    - name: Rust setup
      uses: dtolnay/rust-toolchain@stable

    - name: Rust cache
      uses: swatinem/rust-cache@v2
      with:
        workspaces: './src-tauri -> target'

    - name: Sync node version and setup cache
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
        
    - name: Install frontend dependencies
      run: pnpm install

    - name: Build Changelog
      id: github_release
      uses: mikepenz/release-changelog-builder-action@v3
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build the app
      uses: tauri-apps/tauri-action@v0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NEXT_PUBLIC_GITHUB_AUTH_TOKEN: ${{ secrets.NEXT_PUBLIC_GITHUB_AUTH_TOKEN }}
      with:
        tagName: ${{ github.ref_name }} # This only works if your workflow triggers on new tags.
        releaseName: 'TOTK mod manager v__VERSION__' # tauri-action replaces \_\_VERSION\_\_ with the app version.
        releaseBody: ${{steps.github_release.outputs.changelog}}
        prerelease: true
